import os
import smtplib
import json
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from azure.identity import DefaultAzureCredential
from azure.monitor.query import LogsQueryClient
from openai import OpenAI
import datetime

# Configuration
WORKSPACE_ID = os.environ.get("LOG_ANALYTICS_WORKSPACE_ID")
SMTP_SERVER = os.environ.get("SMTP_SERVER", "smtp.gmail.com")
SMTP_PORT = int(os.environ.get("SMTP_PORT", 587))
SMTP_USERNAME = os.environ.get("SMTP_USERNAME")
SMTP_PASSWORD = os.environ.get("SMTP_PASSWORD")
ALERT_EMAIL_TO = os.environ.get("ALERT_EMAIL_TO", "jayadevarun03@gmail.com")

def query_aks_metrics():
    print("Querying Azure Log Analytics...")
    if not WORKSPACE_ID:
        print("Missing LOG_ANALYTICS_WORKSPACE_ID")
        return None
        
    try:
        credential = DefaultAzureCredential()
        client = LogsQueryClient(credential)
        
        # Query InsightsMetrics for CPU and Memory from the last 15 mins
        query = """
        InsightsMetrics
        | where TimeGenerated > ago(15m)
        | where Namespace == "Processor" or Namespace == "Memory"
        | summarize Average=avg(Val), Max=max(Val) by Computer, Namespace, Name
        """
        response = client.query_workspace(workspace_id=WORKSPACE_ID, query=query, timespan=datetime.timedelta(minutes=15))
        
        if response.status == "Failure":
            print("Query failed")
            return None
        
        results = []
        for table in response.tables:
            for row in table.rows:
                results.append(dict(zip(table.columns, row)))
        
        return results
    except Exception as e:
        print(f"Error querying metrics: {e}")
        return None

def analyze_with_llm(metrics_data):
    print("Analyzing metrics with LLM...")
    if not metrics_data:
        metrics_data = "No metric data returned."
        
    prompt = f"""
You are an expert Site Reliability Engineer (SRE) monitoring an Azure Kubernetes Service (AKS) cluster.
Your job is to analyze the following metrics from the last 15 minutes and determine if an alert should be sent.

Metrics Data:
{json.dumps(metrics_data, indent=2)}

Rules:
1. If CPU Usage (Processor) is consistently near or above 80%, that is an anomaly.
2. If Memory Usage is consistently near or above 80%, that is an anomaly.
3. If data is missing, state that it's healthy for now but flag missing data.

Output exactly a JSON object with the following schema:
{{
    "alert_required": boolean,
    "severity": "High" | "Medium" | "Low" | "None",
    "analysis": "Detailed explanation of your findings",
    "recommendation": "What should the ops team do?"
}}
"""
    try:
        # We must use the langfuse wrapper to trace
        from langfuse.openai import OpenAI as LangfuseOpenAI
        lf_client = LangfuseOpenAI(api_key=os.environ.get("OPENAI_API_KEY"))
        
        response = lf_client.chat.completions.create(
            name="aks-metrics-analysis",
            model="gpt-4o",
            messages=[
                {"role": "system", "content": "You are a helpful AIOps agent."},
                {"role": "user", "content": prompt}
            ],
            response_format={ "type": "json_object" },
            temperature=0.2
        )
        
        result_json = response.choices[0].message.content
        return json.loads(result_json)
    except Exception as e:
        print(f"LLM Analysis failed: {e}")
        return None

def send_alert_email(analysis_result):
    print("Sending alert email...")
    try:
        msg = MIMEMultipart()
        msg['From'] = SMTP_USERNAME
        msg['To'] = ALERT_EMAIL_TO
        msg['Subject'] = f"AIOps Alert: {analysis_result['severity']} Severity Incident"
        
        body = f"""
        <h2>AIOps Cluster Alert</h2>
        <p><strong>Severity:</strong> {analysis_result['severity']}</p>
        <p><strong>Analysis:</strong><br/>{analysis_result['analysis']}</p>
        <p><strong>Recommendation:</strong><br/>{analysis_result['recommendation']}</p>
        <br/>
        <p><em>Generated by Langfuse-traced AIOps Agent</em></p>
        """
        
        msg.attach(MIMEText(body, 'html'))
        
        server = smtplib.SMTP(SMTP_SERVER, SMTP_PORT)
        server.starttls()
        server.login(SMTP_USERNAME, SMTP_PASSWORD)
        text = msg.as_string()
        server.sendmail(SMTP_USERNAME, ALERT_EMAIL_TO, text)
        server.quit()
        print("Email sent successfully!")
    except Exception as e:
        print(f"Failed to send email: {e}")

def main():
    print("Starting AIOps Agent Check...")
    metrics = query_aks_metrics()
    
    if metrics is not None:
        analysis = analyze_with_llm(metrics)
        if analysis:
            print("Analysis Result:")
            print(json.dumps(analysis, indent=2))
            
            if analysis.get("alert_required"):
                print("Alert condition met! Triggering email...")
                send_alert_email(analysis)
            else:
                print("Cluster is healthy. No alert required.")
        else:
            print("Failed to get analysis from LLM.")
    else:
         print("Failed to fetch metrics.")

if __name__ == "__main__":
    main()
